Theta/demo/app/models/blog.py
# -*- coding: utf-8 -*-
"""
    blog
    ~~~~~~~~~~~~~~

    blog definition.

    :copyright: (c) 2016 by fengweimin.
    :date: 16/8/16
"""
from datetime import datetime

from bson.objectid import ObjectId
from werkzeug.utils import cached_property

from app.extensions import mdb
from app.models import User
from app.mongosupport import Model


@mdb.register
class Tag(Model):
    __collection__ = 'tags'
    structure = {
        'name': unicode,
        'weight': int,
        'createTime': datetime,
    }

    required_fields = ['name', 'weight', 'createTime']
    default_values = {'weight': 0, 'createTime': datetime.now}
    indexes = [{'fields': ['name'], 'unique': True}]


@mdb.register
class Post(Model):
    __collection__ = 'posts'
    structure = {
        'uid': ObjectId,
        'pics': [unicode],
        'title': unicode,
        'body': unicode,
        'tids': [ObjectId],  # 相关标签
        'createTime': datetime,
        'viewTimes': int,
        'comments': [{
            'id': int,
            'uid': ObjectId,  # 发表评论人
            'content': unicode,
            'time': datetime,
            'replys': [{
                'uid': ObjectId,  # 发表回复的人
                'rid': ObjectId,  # 接收回复的人
                'content': unicode,
                'time': datetime
            }]
        }]
    }

    required_fields = ['uid', 'title', 'body', 'tids', 'createTime']
    default_values = {'createTime': datetime.now, 'viewTimes': 0}
    indexes = [{'fields': 'tids'}, {'fields': 'createTime'}]

    @cached_property
    def author(self):
        author = User.find_one({'_id': self.uid})
        return author

    @cached_property
    def tags(self):
        ids = list(self.tids)
        tag_dict = {t._id: t for t in Tag.find({'_id': {'$in': ids}})}
        return [tag_dict[id] for id in ids if id in tag_dict]

Theta/demo/app/views/blog.py
# -*- coding: utf-8 -*-
"""
    blog
    ~~~~~~~~~~~~~~

    Blog pages/actions.

    :copyright: (c) 2016 by fengweimin.
    :date: 16/8/16
"""

from datetime import datetime
import time
from binance.client import Client

import pymongo
from bson.objectid import ObjectId
from flask import Blueprint, request, render_template, abort, jsonify, current_app
from flask_babel import gettext as _
from flask_login import current_user, login_required

from app.jobs import post_view_times_counter
from app.models import Post, Tag, User
from app.mongosupport import Pagination, populate_model
from app.tools import send_support_email
from app.tools.decorators import user_not_rejected, user_not_evil
from app.models import Price
import HuobiService
import HuobiUtil
import datetime
import time

blog = Blueprint('blog', __name__)

PAGE_COUNT = 10
# client = Client("BuNN5Z0wbJUiEMXrVCQIRb8ZYZbXynocmKj3mELXSH5YxQXKlAn0yTShG5isui16",
# "n8qXRSLmFKJhBbjvxoGitbKHJ4nfkcOZqtDWXe9p9CMFkhOqAPVjWByGyJ6ixRu2")

huobi_currencys = ['ht', 'usdt', 'btc', 'bch', 'eth', 'xrp', 'ltc', 'ada', 'eos', 'xem', 'dash', 'neo', 'trx', 'icx',
                   'lsk', 'qtum', 'etc', 'btg', 'omg', 'hsr', 'zec', 'steem', 'bts', 'snt', 'salt', 'gnt', 'cmt', 'btm',
                   'pay', 'knc', 'powr', 'bat', 'dgd', 'ven', 'qash', 'zrx', 'gas', 'mana', 'eng', 'cvc', 'mco', 'mtl',
                   'rdn', 'storj', 'chat', 'srn', 'link', 'act', 'tnb', 'qsp', 'req', 'rpx', 'appc', 'rcn', 'smt',
                   'adx', 'tnt', 'ost', 'itc', 'lun', 'gnx', 'ast', 'evx', 'mds', 'snc', 'propy', 'eko', 'nas', 'bcd',
                   'wax', 'wicc', 'topc', 'swftc', 'dbc', 'elf', 'aidoc', 'qun', 'iost', 'yee', 'dat', 'theta', 'let',
                   'dta', 'utk', 'meet', 'zil', 'soc', 'ruff', 'ocn', 'ela', 'bcx', 'sbtc', 'etf', 'bifi', 'zla', 'stk',
                   'wpr', 'mtn', 'mtx', 'edu', 'blz', 'abt', 'ont', 'ctxc', 'bt1', 'bt2']


@blog.route('/')
@blog.route('/index')
def index():
    """
    Index.
    """
    tid = request.args.get('t', None)
    page = int(request.args.get('p', 1))
    start = (page - 1) * PAGE_COUNT
    condition = {}
    if tid:
        condition = {'tids': ObjectId(tid)}
    count = Post.count(condition)
    cursor = Post.find(condition, skip=start, limit=PAGE_COUNT, sort=[('createTime', pymongo.DESCENDING)])
    pagination = Pagination(page, PAGE_COUNT, count)
    return render_template('blog/index.html', posts=list(cursor), pagination=pagination, tags=all_tags())


def all_tags():
    """
    Fetch all tags.
    """
    cursor = Tag.find({}, sort=[('weight', pymongo.DESCENDING)])
    return [t for t in cursor]


@blog.route('/post/<ObjectId:post_id>')
def post(post_id):
    """
    Post.
    """
    p = Post.find_one({'_id': post_id})
    if not p:
        abort(404)

    post_view_times_counter[post_id] += 1

    uids = set()
    for c in p.comments:
        uids.add(c.uid)
        for r in c.replys:
            uids.add(r.uid)
    user_dict = {u._id: u for u in User.find({'_id': {'$in': list(uids)}})}
    return render_template('blog/post.html', id=post_id, post=p, tags=all_tags(), user_dict=user_dict)


@blog.route('/post/new', methods=('GET', 'POST'))
@blog.route('/post/change/<ObjectId:post_id>', methods=('GET', 'POST'))
@login_required
@user_not_rejected
def new(post_id=None):
    # Open page
    if request.method == 'GET':
        p = None
        # Change
        if post_id:
            p = Post.find_one({'_id': post_id})
            if not p:
                abort(404)

        return render_template('blog/new.html', post=p, tags=all_tags())
    # Handle post request
    else:
        try:
            post = populate_model(request.form, Post)
            if not post.title:
                return jsonify(success=False, message=_('Post title can not be blank!'))
            if not post.body:
                return jsonify(success=False, message=_('Post body can not be blank!'))
            if not post.tids:
                return jsonify(success=False, message=_('Post must at least have a tag!'))

            # New
            if not post_id:
                post.uid = current_user._id
                post.save()
                post_id = post._id
                current_app.logger.info('Successfully new a post %s' % post._id)
            # Change
            else:
                existing = Post.find_one({'_id': post_id})
                existing.title = post.title
                existing.tids = post.tids
                existing.body = post.body
                existing.save()
                current_app.logger.info('Successfully change a post %s' % post._id)
        except:
            current_app.logger.exception('Failed when saving post')
            return jsonify(success=False, message=_('Failed when saving the post, please try again later!'))

        return jsonify(success=True, message=_('Save the post successfully.'), pid=str(post_id))


@blog.route('/comment/<ObjectId:post_id>', methods=('POST',))
@login_required
@user_not_rejected
@user_not_evil
def comment(post_id):
    """
    评论博文.
    """
    post = Post.find_one({'_id': post_id})
    if not post:
        return jsonify(success=False, message=_('The post does not exist!'))

    content = request.form.get('content', None)
    if not content or not content.strip():
        return jsonify(success=False, message=_('Comment content can not be blank!'))

    max = -1
    for c in post.comments:
        if max < c.id:
            max = c.id

    now = datetime.now()

    cmt = {
        'id': max + 1,
        'uid': current_user._id,
        'content': content,
        'time': now
    }

    post.comments.insert(0, cmt)
    post.save()

    send_support_email('comment()',
                       u'New comment %s on post %s.' % (content, post._id))

    return jsonify(success=True, message=_('Save comment successfully.'))


@blog.route('/reply/<ObjectId:post_id>/<int:comment_id>', methods=('POST',))
@login_required
@user_not_rejected
@user_not_evil
def reply(post_id, comment_id):
    """
    回复.
    """
    post = Post.find_one({'_id': post_id})
    if not post:
        return jsonify(success=False, message=_('The post does not exist!'))

    content = request.form.get('content', None)
    if not content or not content.strip():
        return jsonify(success=False, message=_('Reply content can not be blank!'))

    cmt = next((c for c in post.comments if c.id == comment_id), -1)
    if cmt == -1:
        return jsonify(success=False, message=_('The comment you would like to reply does not exist!'))

    now = datetime.now()

    reply = {
        'uid': current_user._id,
        'rid': ObjectId(request.form.get('rid', None)),
        'content': content,
        'time': now
    }

    cmt.replys.append(reply)
    post.save()

    send_support_email('reply()', u'New reply %s on post %s.' % (content, post._id))

    return jsonify(success=True, message=_('Save reply successfully.'))


@blog.route('/get/kline_binance', methods=('GET', 'POST'))
def kline_binance():  # 获取binance交易所数据
    client = Client("BuNN5Z0wbJUiEMXrVCQIRb8ZYZbXynocmKj3mELXSH5YxQXKlAn0yTShG5isui16",
                    "n8qXRSLmFKJhBbjvxoGitbKHJ4nfkcOZqtDWXe9p9CMFkhOqAPVjWByGyJ6ixRu2")
    datas = client.get_klines(symbol="LTCBTC", interval="1d")
    for data in datas:
        # 依据日期和交易所名称判断是否在数据库中重复
        existing_ex = Price.find_one({'ex': unicode("binance")})
        existing_date = Price.find_one(
            {'date': unicode(datetime.datetime.utcfromtimestamp(data[0] / 1000).strftime("%Y/%m/%d"))})
        # print('existing:', exiting)
        if not existing_ex or not existing_date:
            price = Price()
            price.date = unicode(datetime.datetime.utcfromtimestamp(data[0] / 1000).strftime("%Y/%m/%d"))
            price.open = float(data[1].encode('utf-8'))
            price.close = float(data[4].encode('utf-8'))
            price.lowest = float(data[3].encode('utf-8'))
            price.highest = float(data[2].encode('utf-8'))
            # price.createTime = datetime.datetime.today()
            price.ex = unicode("binance")
            price.save()
    return jsonify(success=True, message=_('Save the post successfully.'))


# 将unicode字典转化为字符字典
def byteify(input):
    if isinstance(input, dict):
        return {byteify(key): byteify(value)
                for key, value in input.iteritems()}
    elif isinstance(input, list):
        return [byteify(element) for element in input]
    elif isinstance(input, unicode):
        return input.encode('utf-8')
    else:
        return input


@blog.route('/get/kline_huobi', methods=('GET', 'POST'))
def kline_huobi():  # 获取火币交易所数据
    symbol = "btcusdt"
    period = "1day"
    udata = HuobiService.get_kline(symbol, period, 100)  # 返回的key和value是unicode
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
    for data in datas:
        # 依据日期和交易所名称判断是否在数据库中重复
        existing_ex = Price.find_one({'ex': unicode("huobi")})
        existing_date = Price.find_one({'date': unicode(time.strftime('%Y-%m-%d', time.localtime(data['id'])))})
        # print('existing:', exiting)
        if not existing_ex or not existing_date:
            price = Price()
            price.date = unicode(time.strftime('%Y-%m-%d', time.localtime(data['id'])))
            price.open = float(data['open'])
            price.close = float(data['close'])
            price.lowest = float(data['low'])
            price.highest = float(data['high'])
            price.ex = unicode("huobi")
            price.save()
            print('price.date', price.date)
    return jsonify(success=True, message=_('Save the post successfully.'))


# 获取火币所有币种
@blog.route('/get/kline_huobi_currencys', methods=('GET', 'POST'))
def kline_huobi_currencys():  # 获取火币交易所数据
    url = HuobiUtil.MARKET_URL + '/v1/common/currencys'
    params = {}
    udata = HuobiUtil.http_get_request(url, params)  # 返回的key和value是unicode
    datas = byteify(udata)['data']  # 将unicode的key和value转为string

Theta/demo/app/templates/blog/index.html
{% extends "layout.html" %}

{% block title %}{{ _('Blog') }}{% endblock %}

{% block main_inner %}
    <div class="container">
        <div id="posts" class="row">

            <!-- left start -->
            <div class="col-md-8">
                <div class="row">
                    {% for p in posts %}
                        <div class="col-md-12">
                            <div class="panel panel-default panel-border">
                                <div class="panel-heading">
                                    <h3><a href="{{ url_for('blog.post', post_id=p._id) }}">{{ p.title }}</a></h3>
                                    <p class="panel-sub-title font-13 text-muted">
                                        {% for t in p.tags %}
                                            #{{ _(t.name) }}
                                        {% endfor %}
                                    </p>
                                </div>
                                <div class="panel-body">
                                    {{ p.body|striptags|truncate(300) }}
                                </div>
                                <div class="panel-footer">
                                    <span><i class="fa fa-clock-o"></i> {{ p.createTime|timesince }}</span>
                                    <span class="pull-right"><i
                                            class="fa fa-eye pl-10"></i> {{ p.viewTimes }}&nbsp;{{ _('views') }}</span>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="col-md-12">
                            <h2>{{ _('No posts found!') }}</h2>
                        </div>
                    {% endfor %}
                </div>
                {% if pagination.pages > 0 %}
                    <div class="text-center">
                        <ul class="pagination" style="margin-bottom:20px;">
                            {% if pagination.has_prev %}
                                <li><a href="{{ page_base }}?p={{ pagination.page - 1 }}"><</a></li>
                            {% endif %}
                            {% for page in pagination.iter_pages() %}
                                {% if page %}
                                    {% if page != pagination.page %}
                                        <li><a href="{{ page_base }}?p={{ page }}">{{ page }}</a></li>
                                    {% else %}
                                        <li class="active">
                                            <a href="javascript:;">{{ page }}<span class="sr-only">(current)</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                {% else %}
                                    <li><a href="javascript:;">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if pagination.has_next %}
                                <li><a href="{{ page_base }}?p={{ pagination.page + 1 }}">></a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
            <!-- left end -->

            <!-- sidebar start -->
            <div class="col-md-4">
                <div class="m-b-20">
                    <h3>{{ _('Tags') }}</h3>
                    <a href="/blog/index" class="btn btn-primary m-b-5">#{{ _('All') }}</a>
                    {% for t in tags %}
                        <a href="/blog/index?t={{ t._id }}"
                           class="btn btn-primary m-b-5">#{{ _(t.name) }}</a>
                    {% endfor %}
                </div>
                {% if current_user.is_admin %}
                    <div class="panel panel-default">
                        <div class="panel-heading"><h3 class="panel-title">{{ _('Admin') }}</h3></div>
                        <div class="panel-body">
                            <a href="/blog/post/new">{{ _('Add post') }}</a>
                        </div>
                    </div>
                {% endif %}
            </div>
            <!-- sidebar end -->

        </div>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            //
        });
    </script>
{% endblock %}

Theta/demo/app/templates/blog/new.html
{% extends "layout.html" %}

{% block title %}{{ _('Change Post') if post else _('New Post') }}{% endblock %}

{% block style %}
    <link href="{{ base_url() }}/plugins/chosen/chosen.min.css" rel="stylesheet">
    <link href="{{ base_url() }}/plugins/pen/pen.css" rel="stylesheet">
    <style>
        #post-body {
            padding: 12px;
            width: 100%;
            border: 1px solid #ccc;
            background-color: #fff;
            font-size: 18px;
            line-height: 1.42857143;
            min-height: 400px;
        }

        #post-body img {
            max-width: 100%;
        }
    </style>
{% endblock %}

{% block main_inner %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>{{ _('Change Post') if post else _('New Post') }}</h2>
                <form class="m-b-20">
                    <div class="form-group">
                        <label>{{ _('Title') }}</label>
                        <input id="post-title" class="form-control" value="{{ post.title if post else '' }}"/>
                    </div>
                    <div class="form-group">
                        <label>{{ _('Tags') }}</label>
                        <select data-placeholder="{{ _('Choose a tag...') }}" id="post-tags" multiple
                                class="form-control">
                            {% for t in tags %}
                                <option value="{{ t._id }}" {{ 'selected' if post and t._id in post.tids else '' }}>{{ t.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>{{ _('Body') }}</label>
                        <div id="post-body" contenteditable>{{ post.body|safe if post else '' }}</div>
                    </div>
                    <button type="button" class="btn btn-primary" onclick="save($(this))">{{ _('Save') }}</button>
                </form>
            </div>
            <div class="col-md-4">
                <div class="m-b-20">
                    <h3>{{ _('Tags') }}</h3>
                    <a href="/blog/index" class="btn btn-primary">#{{ _('All') }}</a>
                    {% for t in tags %}
                        <a href="/blog/index?t={{ t._id }}"
                           class="btn btn-primary">#{{ _(t.name) }}</a>
                    {% endfor %}
                </div>
                <div>
                    <h3>{{ _('Editing Helps') }}</h3>
                    <p>{{ _('Select to apply effect, click items of toolbar to toggle effects.') }}</p>
                    <p>{{ _('Markdown commands are supported:') }}</p>
                    <ul>
                        <li>{{ _('Headings: type 1~6 <code>#</code> at the line start') }}</li>
                        <li>{{ _('Unordered List: type <code>-</code> or <code>*</code>') }}</li>
                        <li>{{ _('Ordered List: type <code>1.</code>') }}</li>
                        <li>{{ _('Code block: type <strong>```</strong>') }}</li>
                        <li>{{ _('Block Quote: type <code>&gt;</code>') }}</li>
                        <li>{{ _('Horizontal Rule: more than 3 <code>-</code>, <code>*</code>, <code>.</code> will create a <code>&lt;hr /&gt;</code>, like <code>......</code>') }}</li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{{ base_url() }}/plugins/chosen/chosen.jquery.min.js" type="text/javascript"></script>
    <script src="{{ base_url() }}/plugins/pen/pen.js" type="text/javascript"></script>
    <script src="{{ base_url() }}/plugins/pen/markdown.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#post-tags").chosen();
        });

        // Editor
        var options = {
            editor: document.getElementById("post-body"),
            class: "pen",
            debug: false,
            textarea: "<textarea name='content'></textarea>",
            list: [
                'blockquote', 'h2', 'h3', 'p', 'insertorderedlist', 'insertunorderedlist',
                'bold', 'italic', 'underline', 'createlink', 'insertimage'
            ],
            stay: false,
            linksInNewWindow: true
        };
        var editor = new Pen(options);

        function save(btn) {
            if (!editor) {
                return
            }
            if (btn.is(".doing")) {
                return;
            }
            var con = window.confirm("{{ _('Sure to publish this post?') }}");
            if (!con) {
                return false;
            }

            var title = $("#post-title").val();
            var body = $("#post-body").html();
            if (!title) {
                showError("{{ _('Post title can not be blank!') }}");
                return false;
            }
            if (!body) {
                showError("{{ _('Post body can not be blank!') }}");
                return false;
            }

            // Set doing to prevent duplicate clicks
            btn.addClass("doing");
            var method = btn.is("input") ? "val" : "text";
            var oldLabel = btn[method]();
            btn[method](oldLabel + "...");

            var param = {"r": Math.random()};
            {% if post %}
                var action = "/blog/post/change/{{ post._id }}";
            {% else %}
                var action = "/blog/post/new";
            {% endif %}
            param["post.title"] = title;
            param["post.body"] = body;
            $("#post-tags option:selected").each(function (i, n) {
                param["post.tids[" + i + "]"] = $(n).attr("value");
            });

            // Post
            $.post(action, param, function (result) {
                if (result.success) {
                    showSuccess(result.message);
                    location.href = "/blog/post/" + result.pid
                } else {
                    showError(result.message);
                }
                btn.removeClass("doing");
                btn[method](oldLabel);
            }, 'json');
        }
    </script>
{% endblock %}