Theta/demo/app/views/blog.py
# -*- coding: utf-8 -*-
"""
    blog
    ~~~~~~~~~~~~~~

    Blog pages/actions.

    :copyright: (c) 2016 by fengweimin.
    :date: 16/8/16
"""

from datetime import datetime
import time
from binance.client import Client

import pymongo
from bson.objectid import ObjectId
from flask import Blueprint, request, render_template, abort, jsonify, current_app
from flask_babel import gettext as _
from flask_login import current_user, login_required

from app.jobs import post_view_times_counter
from app.models import Post, Tag, User
from app.mongosupport import Pagination, populate_model
from app.tools import send_support_email
from app.tools.decorators import user_not_rejected, user_not_evil
from app.models import Price
import HuobiService
import HuobiUtil
import datetime
import time

blog = Blueprint('blog', __name__)

PAGE_COUNT = 10
# client = Client("BuNN5Z0wbJUiEMXrVCQIRb8ZYZbXynocmKj3mELXSH5YxQXKlAn0yTShG5isui16",
# "n8qXRSLmFKJhBbjvxoGitbKHJ4nfkcOZqtDWXe9p9CMFkhOqAPVjWByGyJ6ixRu2")

huobi_currencys = ['ht', 'usdt', 'btc', 'bch', 'eth', 'xrp', 'ltc', 'ada', 'eos', 'xem', 'dash', 'neo', 'trx', 'icx',
                   'lsk', 'qtum', 'etc', 'btg', 'omg', 'hsr', 'zec', 'steem', 'bts', 'snt', 'salt', 'gnt', 'cmt', 'btm',
                   'pay', 'knc', 'powr', 'bat', 'dgd', 'ven', 'qash', 'zrx', 'gas', 'mana', 'eng', 'cvc', 'mco', 'mtl',
                   'rdn', 'storj', 'chat', 'srn', 'link', 'act', 'tnb', 'qsp', 'req', 'rpx', 'appc', 'rcn', 'smt',
                   'adx', 'tnt', 'ost', 'itc', 'lun', 'gnx', 'ast', 'evx', 'mds', 'snc', 'propy', 'eko', 'nas', 'bcd',
                   'wax', 'wicc', 'topc', 'swftc', 'dbc', 'elf', 'aidoc', 'qun', 'iost', 'yee', 'dat', 'theta', 'let',
                   'dta', 'utk', 'meet', 'zil', 'soc', 'ruff', 'ocn', 'ela', 'bcx', 'sbtc', 'etf', 'bifi', 'zla', 'stk',
                   'wpr', 'mtn', 'mtx', 'edu', 'blz', 'abt', 'ont', 'ctxc', 'bt1', 'bt2']


@blog.route('/')
@blog.route('/index')
def index():
    """
    Index.
    """
    tid = request.args.get('t', None)
    page = int(request.args.get('p', 1))
    start = (page - 1) * PAGE_COUNT
    condition = {}
    if tid:
        condition = {'tids': ObjectId(tid)}
    count = Post.count(condition)
    cursor = Post.find(condition, skip=start, limit=PAGE_COUNT, sort=[('createTime', pymongo.DESCENDING)])
    pagination = Pagination(page, PAGE_COUNT, count)
    return render_template('blog/index.html', posts=list(cursor), pagination=pagination, tags=all_tags())


def all_tags():
    """
    Fetch all tags.
    """
    cursor = Tag.find({}, sort=[('weight', pymongo.DESCENDING)])
    return [t for t in cursor]


@blog.route('/post/<ObjectId:post_id>')
def post(post_id):
    """
    Post.
    """
    p = Post.find_one({'_id': post_id})
    if not p:
        abort(404)

    post_view_times_counter[post_id] += 1

    uids = set()
    for c in p.comments:
        uids.add(c.uid)
        for r in c.replys:
            uids.add(r.uid)
    user_dict = {u._id: u for u in User.find({'_id': {'$in': list(uids)}})}
    return render_template('blog/post.html', id=post_id, post=p, tags=all_tags(), user_dict=user_dict)


@blog.route('/post/new', methods=('GET', 'POST'))
@blog.route('/post/change/<ObjectId:post_id>', methods=('GET', 'POST'))
@login_required
@user_not_rejected
def new(post_id=None):
    # Open page
    if request.method == 'GET':
        p = None
        # Change
        if post_id:
            p = Post.find_one({'_id': post_id})
            if not p:
                abort(404)

        return render_template('blog/new.html', post=p, tags=all_tags())
    # Handle post request
    else:
        try:
            post = populate_model(request.form, Post)
            if not post.title:
                return jsonify(success=False, message=_('Post title can not be blank!'))
            if not post.body:
                return jsonify(success=False, message=_('Post body can not be blank!'))
            if not post.tids:
                return jsonify(success=False, message=_('Post must at least have a tag!'))

            # New
            if not post_id:
                post.uid = current_user._id
                post.save()
                post_id = post._id
                current_app.logger.info('Successfully new a post %s' % post._id)
            # Change
            else:
                existing = Post.find_one({'_id': post_id})
                existing.title = post.title
                existing.tids = post.tids
                existing.body = post.body
                existing.save()
                current_app.logger.info('Successfully change a post %s' % post._id)
        except:
            current_app.logger.exception('Failed when saving post')
            return jsonify(success=False, message=_('Failed when saving the post, please try again later!'))

        return jsonify(success=True, message=_('Save the post successfully.'), pid=str(post_id))


@blog.route('/comment/<ObjectId:post_id>', methods=('POST',))
@login_required
@user_not_rejected
@user_not_evil
def comment(post_id):
    """
    评论博文.
    """
    post = Post.find_one({'_id': post_id})
    if not post:
        return jsonify(success=False, message=_('The post does not exist!'))

    content = request.form.get('content', None)
    if not content or not content.strip():
        return jsonify(success=False, message=_('Comment content can not be blank!'))

    max = -1
    for c in post.comments:
        if max < c.id:
            max = c.id

    now = datetime.now()

    cmt = {
        'id': max + 1,
        'uid': current_user._id,
        'content': content,
        'time': now
    }

    post.comments.insert(0, cmt)
    post.save()

    send_support_email('comment()',
                       u'New comment %s on post %s.' % (content, post._id))

    return jsonify(success=True, message=_('Save comment successfully.'))


@blog.route('/reply/<ObjectId:post_id>/<int:comment_id>', methods=('POST',))
@login_required
@user_not_rejected
@user_not_evil
def reply(post_id, comment_id):
    """
    回复.
    """
    post = Post.find_one({'_id': post_id})
    if not post:
        return jsonify(success=False, message=_('The post does not exist!'))

    content = request.form.get('content', None)
    if not content or not content.strip():
        return jsonify(success=False, message=_('Reply content can not be blank!'))

    cmt = next((c for c in post.comments if c.id == comment_id), -1)
    if cmt == -1:
        return jsonify(success=False, message=_('The comment you would like to reply does not exist!'))

    now = datetime.now()

    reply = {
        'uid': current_user._id,
        'rid': ObjectId(request.form.get('rid', None)),
        'content': content,
        'time': now
    }

    cmt.replys.append(reply)
    post.save()

    send_support_email('reply()', u'New reply %s on post %s.' % (content, post._id))

    return jsonify(success=True, message=_('Save reply successfully.'))


@blog.route('/get/kline_binance', methods=('GET', 'POST'))
def kline_binance():  # 获取binance交易所数据
    client = Client("BuNN5Z0wbJUiEMXrVCQIRb8ZYZbXynocmKj3mELXSH5YxQXKlAn0yTShG5isui16",
                    "n8qXRSLmFKJhBbjvxoGitbKHJ4nfkcOZqtDWXe9p9CMFkhOqAPVjWByGyJ6ixRu2")
    datas = client.get_klines(symbol="LTCBTC", interval="1d")
    for data in datas:
        # 依据日期和交易所名称判断是否在数据库中重复
        existing_ex = Price.find_one({'ex': unicode("binance")})
        existing_date = Price.find_one(
            {'date': unicode(datetime.datetime.utcfromtimestamp(data[0] / 1000).strftime("%Y/%m/%d"))})
        # print('existing:', exiting)
        if not existing_ex or not existing_date:
            price = Price()
            price.date = unicode(datetime.datetime.utcfromtimestamp(data[0] / 1000).strftime("%Y/%m/%d"))
            price.open = float(data[1].encode('utf-8'))
            price.close = float(data[4].encode('utf-8'))
            price.lowest = float(data[3].encode('utf-8'))
            price.highest = float(data[2].encode('utf-8'))
            # price.createTime = datetime.datetime.today()
            price.ex = unicode("binance")
            price.save()
    return jsonify(success=True, message=_('Save the post successfully.'))


# 将unicode字典转化为字符字典
def byteify(input):
    if isinstance(input, dict):
        return {byteify(key): byteify(value)
                for key, value in input.iteritems()}
    elif isinstance(input, list):
        return [byteify(element) for element in input]
    elif isinstance(input, unicode):
        return input.encode('utf-8')
    else:
        return input


@blog.route('/get/kline_huobi', methods=('GET', 'POST'))
def kline_huobi():  # 获取火币交易所数据
    symbol = "btcusdt"
    period = "1day"
    udata = HuobiService.get_kline(symbol, period, 100)  # 返回的key和value是unicode
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
    for data in datas:
        # 依据日期和交易所名称判断是否在数据库中重复
        existing_ex = Price.find_one({'ex': unicode("huobi")})
        existing_date = Price.find_one({'date': unicode(time.strftime('%Y-%m-%d', time.localtime(data['id'])))})
        # print('existing:', exiting)
        if not existing_ex or not existing_date:
            price = Price()
            price.date = unicode(time.strftime('%Y-%m-%d', time.localtime(data['id'])))
            price.open = float(data['open'])
            price.close = float(data['close'])
            price.lowest = float(data['low'])
            price.highest = float(data['high'])
            price.ex = unicode("huobi")
            price.save()
            print('price.date', price.date)
    return jsonify(success=True, message=_('Save the post successfully.'))


# 获取火币所有币种
@blog.route('/get/kline_huobi_currencys', methods=('GET', 'POST'))
def kline_huobi_currencys():  # 获取火币交易所数据
    url = HuobiUtil.MARKET_URL + '/v1/common/currencys'
    params = {}
    udata = HuobiUtil.http_get_request(url, params)  # 返回的key和value是unicode
    datas = byteify(udata)['data']  # 将unicode的key和value转为string

Theta/demo/app/views/seo.py
# -*- coding: utf-8 -*-
"""
    seo
    ~~~~~~~~~~~~~~

    关键词管理相关.

    :copyright: (c) 2016 by fengweimin.
    :date: 16/8/16
"""
from datetime import datetime

import pymongo
import requests
from flask import Blueprint, render_template, request, abort, jsonify, current_app
from lxml import html
from werkzeug.urls import url_quote

from app.models import KeywordLevel, KeywordStatus, Keyword
from app.mongosupport import Pagination
from app.permissions import admin_permission
from app.tools.decorators import async

seo = Blueprint('seo', __name__)

PAGE_COUNT = 100

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36'
headers = {
    'User-Agent': user_agent,
    'Accept': 'application/json, text/javascript, text/html, */*; q=0.01',
    'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4,ja;q=0.2',
    'Accept-Encoding': 'gzip, deflate, sdch',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'X-Requested-With': 'XMLHttpRequest',
    'Connection': 'keep-alive',
}
adapter = requests.adapters.HTTPAdapter(max_retries=5)
ss = requests.session()
ss.mount('http://', adapter)
ss.mount('https://', adapter)
ss.headers.update(headers)


@seo.route('/')
@seo.route('/index')
@admin_permission.require(403)
def index():
    """
    关键词管理首页, 列举站点级别的关键词, 并支持简单查询和翻页.
    """
    s = request.args.get('status', u'bare,processed,repeated')
    k = request.args.get('keyword', '')
    o = request.args.get('owner', '')
    p = int(request.args.get('page', '1'))
    start = (p - 1) * PAGE_COUNT

    condition = {'level': KeywordLevel.SITE}
    if k:
        condition['name'] = k.strip()
    if o:
        condition['owner'] = o.strip()
    status = s.split(u',')
    if status:
        condition['status'] = {'$in': status}

    count = Keyword.count(condition)
    cursor = Keyword.find(condition, skip=start, limit=PAGE_COUNT, sort=[('baiduIndex', pymongo.DESCENDING)])
    keywords = []
    for c in cursor:
        set_index(c)
        keywords.append(c)
    pagination = Pagination(p, PAGE_COUNT, count)
    return render_template('seo/index.html', keywords=keywords, pagination=pagination)


def set_index(k):
    """
    设置关键字的优化难易度, 仅供参考.
    """
    if k.baiduResult != 0:
        index = float(k.baiduIndex) / k.baiduResult
    else:
        index = 0
    k.index = round(index * 10000, 1)


@seo.route('/longtail/<ObjectId:keyword_id>')
@admin_permission.require(403)
def longtail(keyword_id):
    """
    获取指定站点关键字下的长尾关键字.
    """
    keyword = Keyword.find_one({'_id': keyword_id})
    if not keyword:
        abort(404)

    s = request.args.get('status', u'bare,processed,repeated')
    p = int(request.args.get('page', '1'))
    start = (p - 1) * PAGE_COUNT
    condition = {'level': KeywordLevel.LONG_TAIL, 'parentId': keyword_id}
    status = s.split(u',')
    if status:
        condition['status'] = {'$in': status}

    count = Keyword.count(condition)
    cursor = Keyword.find(condition, skip=start, limit=PAGE_COUNT, sort=[('baiduIndex', pymongo.DESCENDING)])
    keywords = []
    for c in cursor:
        keywords.append(c)
    pagination = Pagination(p, PAGE_COUNT, count)

    return render_template('seo/longtail.html', keyword=keyword, keywords=keywords, pagination=pagination)


@seo.route('/hearsay/<ObjectId:keyword_id>', methods=('GET', 'POST'))
@admin_permission.require(403)
def hearsay(keyword_id):
    """
    编辑关键字对应的文章.
    """
    keyword = Keyword.find_one({'_id': keyword_id})
    if not keyword:
        abort(404)

    # Open page
    if request.method == 'GET':
        return render_template('seo/hearsay.html', keyword=keyword)
    # Handle post request
    else:
        current_app.logger.info('Try to save hearsay for keyword %s/%s' % (keyword._id, keyword.name))
        title = request.form.get('title', '')
        body = request.form.get('body', '')
        if not title:
            return jsonify(success=False, message='文章标题不能为空！')
        if not body:
            return jsonify(success=False, message='文章内容不能为空！')

        is_new = True if not keyword.hearsay else False
        keyword.hearsay.title = title
        keyword.hearsay.body = body
        keyword.updateTime = datetime.now()
        if is_new:
            keyword.status = KeywordStatus.PROCESSED

        keyword.save()

        if not current_app.debug and is_new:
            notify_baidu(current_app._get_current_object(), keyword._id)

        return jsonify(success=True, message='成功保存了你的文章。')


@async
def notify_baidu(app, id):
    """
    主动将新建文章的url主动推送到百度.
    参考自 http://zhanzhang.baidu.com/linksubmit/index?site=http://www.girl-atlas.com/
    """
    url = 'http://www.girl-atlas.com/hearsay/%s' % id
    app.logger.info('Try to nofity baidu this new url %s' % url)
    with app.app_context():
        j = requests.post('http://data.zz.baidu.com/urls?site=www.girl-atlas.com&token=umKKIO97UfMdq9P6',
                          data=url, headers={'Content-Type': 'text/plain'}).json()
        app.logger.info('Notify baidu result is %s' % j)


@seo.route('/refresh/<ObjectId:keyword_id>', methods=('POST',))
@admin_permission.require(403)
def refresh(keyword_id):
    """
    刷新一个指定关键字的长尾关键字.
    """
    keyword = Keyword.find_one({'_id': keyword_id})
    if not keyword:
        abort(404)

    analyze_keyword(current_app._get_current_object(), keyword)
    return jsonify(success=True, message='成功触发了刷新请求，请稍候查看最新数据。')


@async
def analyze_keyword(app, keyword):
    """
    分析站点级别的关键字, 获取其百度指数以及其相关的长尾关键字.
    目前是从5118抓取.
    """
    app.logger.info('Try to analyze keyword %s/%s' % (keyword._id, keyword.name))

    ss.headers['Referer'] = 'http://www.5118.com/'
    t = ss.get('http://www.5118.com/seo/words/%s' % url_quote(keyword.name)).text
    tree = html.fromstring(t)
    dls = tree.xpath('//div[@class="Fn-ui-list dig-list"]/dl')
    total = len(dls)
    for dl in dls:
        if dl.get('class', '') == 'dl-word':
            continue
        name = unicode(dl.xpath('./dd[1]//a[1]/@title')[0].strip())
        baidu_index = dl.xpath('./dd[2]/text()')[0].strip()
        baidu_result = dl.xpath('./dd[3]/text()')[0].strip()
        if not baidu_index.isdigit():
            baidu_index = 0
        if not baidu_result.isdigit():
            baidu_result = 0
        app.logger.info('Found keyword: %s/%s/%s' % (name, baidu_index, baidu_result))

        if name == keyword.name:
            keyword.baiduIndex = int(baidu_index)
            keyword.baiduResult = int(baidu_result)
            if total > 2:
                keyword.total = total - 2
            keyword.save()
        else:
            long_tail = Keyword.find_one({'name': name})
            if not long_tail:
                long_tail = Keyword()
                long_tail.name = name
                long_tail.level = KeywordLevel.LONG_TAIL
                long_tail.parentId = keyword._id

            long_tail.baiduIndex = int(baidu_index)
            long_tail.baiduResult = int(baidu_result)
            long_tail.save()

Theta/demo/app/templates/_macros.html
{% macro base_url() %}/static{% endmacro %}

Theta/demo/app/templates/layout.html
{% from "_macros.html" import base_url with context %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block seo %}
        <meta name="description" content="flask-boot">
        <meta name="keywords" content="">
    {% endblock %}
    <meta name="author" content="">

    <title>{% block title %}{{ _('Flask-Boot') }}{% endblock %}</title>

    <link rel="shortcut icon" href="{{ base_url() }}/img/favicon.ico">
    <link href="{{ base_url() }}/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="{{ base_url() }}/css/core.css" rel="stylesheet" type="text/css"/>
    <link href="{{ base_url() }}/css/components.css" rel="stylesheet" type="text/css"/>
    <link href="{{ base_url() }}/css/icons.css" rel="stylesheet" type="text/css"/>
    <link href="{{ base_url() }}/css/menu.css" rel="stylesheet" type="text/css"/>
    <link href="{{ base_url() }}/css/responsive.css" rel="stylesheet" type="text/css"/>
    <link href="{{ base_url() }}/css/pages.css" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="{{ base_url() }}/js/modernizr.min.js"></script>

    {% block style %}
    {% endblock %}
</head>

<body>
{% block header %}
    <!-- Navigation Bar-->
    <header id="topnav">
        <div class="topbar-main">
            <div class="container">

                <!-- Logo container-->
                <div class="logo">
                    <a href="/" class="logo"><span>{{ _('Flask-Boot') }}</span></a>
                </div>
                <!-- End Logo container-->

                <div class="menu-extras">

                    <ul class="nav navbar-nav navbar-right pull-right">
                        <li>
                            <form role="search" class="navbar-left app-search pull-left hidden-xs">
                                <input type="text" placeholder="{{ _('Search...') }}" class="form-control">
                                <a href=""><i class="fa fa-search"></i></a>
                            </form>
                        </li>

                        {% if current_user.is_authenticated %}
                            <li class="dropdown hidden-xs">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-bell"></i> <span class="badge badge-xs badge-pink">3</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-lg">
                                    <li class="text-center notifi-title">{{ _('Notifications') }}</li>
                                    <li class="list-group nicescroll notification-list">
                                        <a href="javascript:coming();" class="list-group-item">
                                            {{ _('No unread notifications.') }}
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);" class=" text-right">
                                            <small><b>{{ _('All Notifications') }}</b></small>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle profile" data-toggle="dropdown">
                                    <img src="{{ current_user.head if user and user.head else '/static/img/avatar.png' }}"
                                         alt="user-img"
                                         class="img-circle">
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-header">{{ _('Welcome, ') }}{{ current_user.name }}</li>
                                    <li><a href="javascript:coming();"><i class="ti-user m-r-5"></i> {{ _('Profile') }}
                                    </a></li>
                                    <li><a href="{{ url_for('public.logout') }}"><i class="ti-power-off m-r-5"></i>
                                        {{ _('Logout') }}</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="{{ 'active' if request.endpoint and request.endpoint.startswith(('public.login', 'public.signup')) }}">
                                <a href="{{ url_for('public.login') }}">{{ _('Login') }}</a>
                            </li>
                        {% endif %}
                    </ul>

                    <div class="menu-item">
                        <!-- Mobile menu toggle-->
                        <a class="navbar-toggle">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>
                        <!-- End mobile menu toggle-->
                    </div>
                </div>

            </div>
        </div>
        <!-- End topbar -->

        <!-- Navbar Start -->
        <div class="navbar-custom">
            <div class="container">
                <div id="navigation">
                    <!-- Navigation Menu-->
                    <ul class="navigation-menu">
                        <li class="{{ 'active' if request.endpoint and request.endpoint == 'public.index' }}">
                            <a href="/"><i class="fa fa-home"></i>{{ _('Index') }}</a>
                        </li>
                        <li class="{{ 'active' if request.endpoint and request.endpoint.startswith('blog') }}">
                            <a href="{{ url_for('blog.index') }}"><i class="fa fa-book"></i>{{ _('Blog') }}</a>
                        </li>
                        <li class="has-submenu {{ 'active' if request.endpoint and request.endpoint.startswith(('public.blank', 'public.styleguide')) }}">
                            <a href="#"><i class="fa fa-info-circle"></i>{{ _('Pages') }} <span
                                    class="caret"></span></a>
                            <ul class="submenu">
                                <li><a href="{{ url_for('public.blank') }}">{{ _('Blank Page') }}</a></li>
                                <li><a href="{{ url_for('public.styleguide') }}">{{ _('Style Guide') }}</a></li>
                                <li><a href="{{ url_for('crud.index') }}">CRUD</a></li>
                                <li><a href="{{ url_for('seo.index') }}">SEO</a></li>
                            </ul>
                        </li>

                    </ul>
                    <!-- End navigation menu -->
                </div> <!-- end #navigation -->
            </div> <!-- end container -->
        </div> <!-- end navbar-custom -->
    </header>
    <!-- End Navigation Bar-->
{% endblock %}

{% block main %}
    <div class="wrapper">
        {% block main_inner %}
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>{{ _('Flask-Boot') }}</h1>
                        <p>{{ _('Superfast project prototyping!') }}</p>
                    </div>
                </div>
            </div> <!-- end container -->
        {% endblock %}
    </div>
    <!-- End wrapper -->
{% endblock %}

{% block footer %}
    <!-- Footer -->
    <footer class="footer text-right">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    2016 © {{ _('Flask-Boot') }}
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
{% endblock %}

<a id="scroll-to-top">
    <i class="fa fa-angle-up"></i>
</a>

<!-- jQuery  -->
<script src="{{ base_url() }}/js/jquery.min.js"></script>
<script src="{{ base_url() }}/js/bootstrap.min.js"></script>
<script src="{{ base_url() }}/js/detect.js"></script>
<script src="{{ base_url() }}/js/fastclick.js"></script>
<script src="{{ base_url() }}/js/jquery.bootstrap-growl.min.js"></script>
<script src="{{ base_url() }}/js/jquery.app.js"></script>

{% block script %}
{% endblock %}

</body>
</html>